export type Product = {
  id: number;
  name: string;
  variant: string;
  price: number;
  originalPrice: number | null;
  image: string;
  backImage?: string;
  isSale: boolean;
  inStock?: boolean;
  brand?: string;
  tagline?: string;
  collection: "featured" | "shop";
  category: "Tees" | "Bottoms" | "Hoodies" | "Outerwear";
};

export const products: Product[] = [
  // --- Featured Collection (Home Page) ---
  {
    id: 2,
    name: "Tiger Design Tee",
    variant: "BLACK",
    price: 1699,
    originalPrice: 2199,
    image: "/products/tiger-tshirt.jpeg",
    backImage: "/products/apsara-aura-black-tee-back.jpeg",
    isSale: true,
    inStock: true,
    tagline: "Hand Embroidery & Puff Print",
    collection: "featured",
    category: "Tees",
  },
  {
    id: 5,
    name: "Apsara Aura Tee",
    variant: "BLACK",
    price: 1699,
    originalPrice: 2199,
    image: "/products/apsara-aura-poster.jpeg",
    isSale: true,
    inStock: true,
    tagline: "Oversized Fit",
    collection: "featured",
    category: "Tees",
  },
  {
    id: 6,
    name: "Rage Tiger Tee",
    variant: "BLACK",
    price: 1599,
    originalPrice: 2099,
    image: "/products/blue-lips-navy-tee-back.jpeg",
    backImage: "/products/rage-tiger-black-tee-back.jpeg",
    isSale: true,
    inStock: true,
    tagline: "260 GSM",
    collection: "featured",
    category: "Tees",
  },
  {
    id: 11,
    name: "Logo Tee",
    variant: "BLACK",
    price: 1299,
    originalPrice: 1699,
    image: "/products/love-simulation-yellow-poster-alt.jpeg",
    isSale: true,
    inStock: true,
    tagline: "Oversized Fit",
    collection: "featured",
    category: "Tees",
  },

  // --- Shop Collection (Shop Page) ---
  {
    id: 12,
    name: "Bombay Sapphire Tee",
    variant: "SAGE GREEN",
    price: 1499,
    originalPrice: 1999,
    image: "/products/bombay-sapphire-sage-tee-front.jpeg",
    backImage: "/products/bombay-sapphire-sage-tee-back.jpeg",
    isSale: false,
    inStock: true,
    tagline: "Vintage Wash",
    collection: "shop",
    category: "Tees",
  },
  {
    id: 13,
    name: "Love Simulation Red",
    variant: "RED",
    price: 1599,
    originalPrice: 2099,
    image: "/products/love-simulation-red-poster.jpeg",
    backImage: "/products/love-simulation-red-poster-alt.jpeg",
    isSale: true,
    inStock: true,
    tagline: "High Def Print",
    collection: "shop",
    category: "Tees",
  },
  {
    id: 14,
    name: "Sugar Daddy Blue",
    variant: "BLUE",
    price: 1799,
    originalPrice: 2299,
    image: "/products/sugar-daddy-blue-poster.jpeg",
    backImage: "/products/sugar-daddy-blue-poster-alt.jpeg",
    isSale: true,
    inStock: true,
    tagline: "Premium Heavyweight",
    collection: "shop",
    category: "Tees",
  },
  {
    id: 15,
    name: "Sugar Daddy Brown",
    variant: "BROWN",
    price: 1699,
    originalPrice: 2199,
    image: "/products/sugar-daddy-brown-poster.jpeg",
    backImage: "/products/sugar-daddy-brown-poster-alt.jpeg",
    isSale: true,
    inStock: true,
    tagline: "Neutral Tones",
    collection: "shop",
    category: "Tees",
  },
  {
    id: 16,
    name: "Slim Shady Navy",
    variant: "NAVY",
    price: 1399,
    originalPrice: 1799,
    image: "/products/slim-shady-navy-tee-back.jpeg",
    backImage: "/products/slim-shady-navy-tee-back-alt.jpeg",
    isSale: false,
    inStock: true,
    tagline: "Streetwear Fit",
    collection: "shop",
    category: "Tees",
  },
  {
    id: 17,
    name: "Apsara Aura White",
    variant: "WHITE",
    price: 1699,
    originalPrice: 2199,
    image: "/products/rangvirangi-pink-logo-black-tee-front.jpeg",
    isSale: false,
    inStock: true,
    tagline: "Signature Series",
    collection: "shop",
    category: "Tees",
  },
  {
    id: 18,
    name: "Tiger Mask Tee",
    variant: "GRAY",
    price: 1499,
    originalPrice: 1999,
    image: "/products/tiger-tshirt.jpeg",
    isSale: false,
    inStock: true,
    tagline: "Minimalist Graphic",
    collection: "shop",
    category: "Tees",
  },
  {
    id: 19,
    name: "Yellow Aura Tee",
    variant: "YELLOW",
    price: 1599,
    originalPrice: 2099,
    image: "/products/love-simulation-yellow-poster.jpeg",
    isSale: true,
    inStock: true,
    tagline: "Limited Edition",
    collection: "shop",
    category: "Tees",
  },
];
