export type Product = {
  id: number;
  name: string;
  variant: string;
  price: number;
  originalPrice: number | null;
  image: string;
  backImage?: string;
  isSale: boolean;
  inStock?: boolean;
  brand?: string;
  tagline?: string;
  description?: string;
  gsm?: number | string;
  fabric?: string;
  print?: string;
  highlights?: string[];
  fit?: string;
  collection: "featured" | "shop";
  category: "Tees" | "Bottoms" | "Hoodies" | "Outerwear";
};

export const products: Product[] = [
  // --- Featured Collection (Home Page) ---
  {
    id: 2,
    name: "Tiger Oversized T-Shirt",
    variant: "BLACK",
    price: 1505,
    originalPrice: 2199,
    image: "/products/tiger-tshirt.jpeg",
    isSale: true,
    inStock: true,
    tagline: "Hand Embroidery & Puff Print",
    fabric: "270 GSM Premium Cotton",
    gsm: 270,
    print: "Hand Embroidery + Puff Screen Print",
    fit: "Oversized",
    description: "The Tiger Oversized Tee represents strength, detail, and craftsmanship. Built from 270 GSM heavyweight cotton, this t-shirt feels substantial while maintaining softness against the skin. The design combines hand embroidery with puff screen printing, creating a layered texture that elevates the artwork beyond regular printed tees.",
    highlights: [
      "Ultra heavyweight 270 GSM cotton",
      "Hand embroidered artwork",
      "Puff screen print texture",
      "Premium oversized streetwear fit",
      "Deep black colourway"
    ],
    collection: "featured",
    category: "Tees",
  },
  {
    id: 6,
    name: "Tiger Rage Oversized T-Shirt",
    variant: "BLACK",
    price: 1505,
    originalPrice: 2099,
    image: "/products/blue-lips-navy-tee-back.jpeg",
    isSale: true,
    inStock: true,
    tagline: "Puff Screen Print + HD Print",
    fabric: "260 GSM Premium Cotton",
    gsm: 260,
    print: "Puff Screen Print + HD Print",
    fit: "Oversized",
    description: "The Tiger Rage Tee captures raw energy and fearless design. Constructed from 260 GSM premium cotton, it balances durability with breathable comfort. The front artwork uses a combination of puff screen print and HD printing, creating a dynamic visual effect with raised texture and sharp graphic clarity.",
    highlights: [
      "260 GSM heavyweight cotton",
      "HD graphic printing",
      "Puff screen print texture",
      "Relaxed oversized silhouette",
      "Black streetwear colourway"
    ],
    collection: "featured",
    category: "Tees",
  },
  {
    id: 11,
    name: "Logo Tee",
    variant: "BLACK",
    price: 1299,
    originalPrice: 1699,
    image: "/products/love-simulation-yellow-poster-alt.jpeg",
    isSale: true,
    inStock: true,
    tagline: "Oversized Fit",
    collection: "featured",
    category: "Tees",
  },

  // --- Shop Collection (Shop Page) ---
  {
    id: 12,
    name: "Bombay Sapphire Oversized T-Shirt",
    variant: "SAGE GREEN",
    price: 909,
    originalPrice: 1999,
    image: "/products/bombay-sapphire-sage-tee-front.jpeg",
    isSale: false,
    inStock: true,
    tagline: "Neck Embroidery + Back Digital Print",
    fabric: "260 GSM Premium Cotton",
    gsm: 260,
    print: "Neck Embroidery + Back Digital Print",
    fit: "Oversized",
    description: "The Bombay Sapphire Tee blends subtle detailing with bold back graphics. Made from 260 GSM premium cotton, it provides durability, breathability, and everyday comfort. A unique highlight is the delicate embroidery around the front neckline, adding a refined touch rarely seen in streetwear tees.",
    highlights: [
      "260 GSM premium cotton",
      "Embroidered neckline detailing",
      "High quality back digital print",
      "Relaxed oversized fit",
      "Available in White and Cyan"
    ],
    collection: "shop",
    category: "Tees",
  },
  {
    id: 13,
    name: "Aishwarya – Apsara Aura Oversized T-Shirt",
    variant: "RED",
    price: 1202,
    originalPrice: 2099,
    image: "/products/rangvirangi-pink-logo-black-tee-front-alt.jpeg",
    isSale: true,
    inStock: true,
    tagline: "Full Digital Print",
    fabric: "310 GSM Cotton Terry",
    gsm: 310,
    print: "Full Digital Print (Front & Back)",
    fit: "Oversized",
    description: "Inspired by divine beauty and elegance, the Aishwarya – Apsara Aura Tee transforms art into fashion. Crafted from premium 310 GSM cotton terry, this heavyweight tee delivers unmatched comfort and luxury. The design features full-coverage digital artwork across the front and back.",
    highlights: [
      "310 GSM premium cotton terry",
      "Full digital artwork front and back",
      "Ultra-premium heavyweight feel",
      "Relaxed oversized fit",
      "Artistic statement design"
    ],
    collection: "shop",
    category: "Tees",
  },
  {
    id: 15,
    name: "Sugar Daddy Oversized T-Shirt",
    variant: "BROWN",
    price: 1505,
    originalPrice: 2199,
    image: "/products/sugar-daddy-brown-poster.jpeg",
    isSale: true,
    inStock: true,
    tagline: "Puff Screen Print",
    fabric: "260 GSM Premium Cotton",
    gsm: 260,
    print: "Puff Screen Print",
    fit: "Oversized Streetwear Fit",
    description: "The Sugar Daddy Oversized Tee is built for bold personalities who like their fashion loud and confident. Crafted from 260 GSM heavyweight premium cotton, this tee delivers both structure and comfort. The design features high-quality puff screen printing, giving the artwork a raised 3D texture.",
    highlights: [
      "260 GSM heavyweight cotton",
      "Premium puff screen print design",
      "Soft, breathable fabric",
      "Relaxed oversized streetwear fit",
      "Available in Blue and Red"
    ],
    collection: "shop",
    category: "Tees",
  },
  {
    id: 16,
    name: "Slim Shady Navy",
    variant: "NAVY",
    price: 1399,
    originalPrice: 1799,
    image: "/products/slim-shady-navy-tee-back.jpeg",
    isSale: false,
    inStock: true,
    tagline: "Streetwear Fit",
    collection: "shop",
    category: "Tees",
  },
  {
    id: 17,
    name: "Apsara Aura White",
    variant: "WHITE",
    price: 1202,
    originalPrice: 2199,
    image: "/products/rangvirangi-pink-logo-black-tee-front.jpeg",
    isSale: false,
    inStock: true,
    tagline: "Full Digital Print",
    fabric: "310 GSM Cotton Terry",
    gsm: 310,
    print: "Full Digital Print (Front & Back)",
    fit: "Oversized",
    description: "Inspired by divine beauty and elegance, the Aishwarya – Apsara Aura Tee transforms art into fashion. Crafted from premium 310 GSM cotton terry, this heavyweight tee delivers unmatched comfort and luxury.",
    highlights: [
      "310 GSM premium cotton terry",
      "Full digital artwork front and back",
      "Ultra-premium heavyweight feel",
      "Relaxed oversized fit"
    ],
    collection: "shop",
    category: "Tees",
  },
  {
    id: 18,
    name: "Tiger Mask Tee",
    variant: "GRAY",
    price: 1505,
    originalPrice: 1999,
    image: "/products/tiger-tshirt.jpeg",
    isSale: false,
    inStock: true,
    tagline: "Minimalist Graphic",
    collection: "shop",
    category: "Tees",
  },
  {
    id: 996,
    name: "Music Oversized T-Shirt",
    variant: "WHITE",
    price: 1202,
    originalPrice: 1999,
    image: "/culture-white-front.jpg",
    isSale: true,
    inStock: true,
    tagline: "Digital Print (Front & Back)",
    fabric: "310 GSM Cotton Terry",
    gsm: 310,
    print: "Digital Print (Front & Back)",
    fit: "Oversized",
    description: "The Music Oversized Tee is designed for people who live through rhythm and culture. Made from luxurious 310 GSM cotton terry, this t-shirt offers exceptional softness, thickness, and premium comfort. Both the front and back feature detailed digital prints.",
    highlights: [
      "Premium 310 GSM cotton terry fabric",
      "High-resolution digital prints",
      "Heavyweight luxury feel",
      "Oversized streetwear fit",
      "Clean white base colour"
    ],
    collection: "featured",
    category: "Tees",
  },
  {
    id: 997,
    name: "Sugar Daddy Oversized T-Shirt",
    variant: "NAVY BLUE",
    price: 1505,
    originalPrice: 1999,
    image: "/sugar-daddy-tee.jpg",
    isSale: true,
    inStock: true,
    tagline: "Puff Screen Print",
    fabric: "260 GSM Premium Cotton",
    gsm: 260,
    print: "Puff Screen Print",
    fit: "Oversized Streetwear Fit",
    description: "The Sugar Daddy Oversized Tee is built for bold personalities who like their fashion loud and confident. Crafted from 260 GSM heavyweight premium cotton, this tee delivers both structure and comfort.",
    highlights: [
      "260 GSM heavyweight cotton",
      "Premium puff screen print design",
      "Relaxed oversized streetwear fit"
    ],
    collection: "featured",
    category: "Tees",
  },
  {
    id: 998,
    name: "Love Simulation Oversized T-Shirt",
    variant: "WHITE",
    price: 1095,
    originalPrice: 1999,
    image: "/love-tee-mock.jpg",
    isSale: true,
    inStock: true,
    tagline: "Full Back Digital Print + HD Print",
    fabric: "260 GSM Premium Cotton",
    gsm: 260,
    print: "Full Back Digital Print + HD Print",
    fit: "Oversized Fit",
    description: "The Love Simulation Tee blends futuristic graphics with modern streetwear aesthetics. Made from 260 GSM premium cotton, the fabric provides durability while maintaining everyday comfort. The standout feature is its fully detailed back artwork created with high-definition digital printing.",
    highlights: [
      "Heavyweight 260 GSM cotton",
      "Full back HD digital print",
      "Sharp graphic detailing",
      "Comfortable oversized fit",
      "Available in White and Red"
    ],
    collection: "featured",
    category: "Tees",
  },
  {
    id: 999,
    name: "Bombay Sapphire Oversized T-Shirt",
    variant: "WHITE",
    price: 909,
    originalPrice: 1999,
    image: "/artwork.jpg",
    backImage: "/tee-back.jpg",
    isSale: true,
    inStock: true,
    tagline: "Neck Embroidery + Back Digital Print",
    fabric: "260 GSM Premium Cotton",
    gsm: 260,
    print: "Neck Embroidery + Back Digital Print",
    fit: "Oversized",
    description: "The Bombay Sapphire Tee blends subtle detailing with bold back graphics. Made from 260 GSM premium cotton, it provides durability, breathability, and everyday comfort. A unique highlight is the delicate embroidery around the front neckline.",
    highlights: [
      "260 GSM premium cotton",
      "Embroidered neckline detailing",
      "High quality back digital print",
      "Relaxed oversized fit"
    ],
    collection: "featured",
    category: "Tees",
  },
];
